
-- Clear existing sample projects and insert your real projects
DELETE FROM public.projects;

-- Insert your actual projects
INSERT INTO public.projects (title, description, tech_stack, github_url, live_url, image_url, category, features, is_featured, display_order) VALUES
('BAUCF Choir Management Web App', 'A custom-built platform to help manage choir operations for BAUCF. The app centralizes attendance tracking, song and lyric management, member roles, and rehearsal scheduling. It streamlines communication and makes team coordination easier for church leadership.', ARRAY['React.js', 'Node.js', 'MongoDB'], 'https://github.com/mervine-choir-app', 'https://baucf-choir.demo.com', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80', 'Productivity', ARRAY['Member profiles and attendance tracking', 'Song library with media team export', 'Role assignment and task tracking', 'Event and rehearsal calendar'], true, 1),

('MIRA – AI Academic Assistant', 'MIRA is an AI-powered academic assistant built to support students with planning, studying, and learning. It summarizes texts, tracks deadlines, answers academic questions, and offers personalized study insights—all powered by large language models.', ARRAY['Python', 'FastAPI', 'OpenAI API', 'Firebase', 'TailwindCSS'], 'https://github.com/mervine-mira-ai', 'https://mira-assistant.demo.com', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80', 'AI', ARRAY['AI-generated summaries and flashcards', 'Smart planner with custom reminders', 'File uploads and annotation', 'Personalized learning tips'], true, 2),

('GD Pastries – Website & Online Store', 'A clean, elegant website and online store for a local pastry business. Built to showcase products, accept orders, and reflect the warmth and creativity of the brand. The site includes dynamic product pages, order forms, and payment integration.', ARRAY['HTML/CSS', 'JavaScript', 'Firebase', 'Stripe API'], 'https://github.com/mervine-gd-pastries', 'https://gd-pastries.demo.com', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=80', 'E-Commerce', ARRAY['Product gallery and details', 'Online ordering and contact form', 'Secure checkout with payment integration', 'Admin panel for product updates'], true, 3),

('ExpenseMate – AI Budgeting Assistant', 'A personal budgeting app designed for natural spenders who want to take control of their money. It uses zero-based budgeting principles and AI to analyze spending patterns, provide financial insights, and offer saving suggestions.', ARRAY['React.js', 'Flask', 'Python', 'OpenAI API'], 'https://github.com/mervine-expensemate', 'https://expensemate.demo.com', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop&q=80', 'AI', ARRAY['Monthly budget planner', 'AI-generated summaries and alerts', 'Income vs expense breakdown', 'Spending forecasts and trends'], true, 4);
