// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiqpjsefbofwvbbvzrib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcXBqc2VmYm9md3ZiYnZ6cmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTA5NTcsImV4cCI6MjA2MjYyNjk1N30.U-HaBtCsPIlGH08DMA9HoMMUg-oH19wOHkuqaq_BYuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);